/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomeInput: typeof import('./components/CustomeInput.vue')['default']
    CustomeLabel: typeof import('./components/CustomeLabel.vue')['default']
    CustomeSelect: typeof import('./components/CustomeSelect.vue')['default']
    Form: typeof import('./components/FormComponent.vue')['default']
    FormComponent: typeof import('./components/FormComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
